from typing import Iterable


class CliffordTGate:
    @staticmethod
    def X(qubit: int) -> CliffordTGate: ...
    @staticmethod
    def Y(qubit: int) -> CliffordTGate: ...
    @staticmethod
    def Z(qubit: int) -> CliffordTGate: ...
    @staticmethod
    def S(qubit: int) -> CliffordTGate: ...
    @staticmethod
    def Sdg(qubit: int) -> CliffordTGate: ...
    @staticmethod
    def H(qubit: int) -> CliffordTGate: ...
    @staticmethod
    def T(qubit: int) -> CliffordTGate: ...
    @staticmethod
    def Tdg(qubit: int) -> CliffordTGate: ...
    @staticmethod
    def Cnot(control: int, target: int) -> CliffordTGate: ...
    @staticmethod
    def Cz(control: int, target: int) -> CliffordTGate: ...

class CliffordTCircuit:
    def __init__(self, qubits: int, gates: Iterable[CliffordTGate]) -> None: ...
    @staticmethod
    def random(qubits: int, gates: int, t_gates: int, seed: int) -> CliffordTCircuit: ...

    @property
    def qubits(self) -> int: ...
    @property
    def t_gates(self) -> int: ...
    @property
    def gates(self) -> list[CliffordTGate]: ...


def simulate_circuit(w: str, circuit: CliffordTCircuit) -> complex: ...
def simulate_circuit_gpu(w: str, circuit: CliffordTCircuit) -> complex: ...
