name: Benchmark Baseline

on:
    push:
        branches: main

jobs:
    benchmark_base_branch:
        name: Benchmark baseline
        permissions:
            checks: write
        runs-on: self-hosted
        container:
            image: localhost:5000/qlit-bench-runner
        steps:
            - uses: actions/checkout@v6
            - uses: bencherdev/bencher@main
            - uses: moonrepo/setup-rust@v1
              with:
                  cache-target: release
            - uses: astral-sh/setup-uv@v7
              with:
                  enable-cache: true
            - run: uv sync --locked
            - name: Run Python benchmarks
              run: |
                  bencher run \
                  --project qlit \
                  --token '${{ secrets.BENCHER_API_TOKEN }}' \
                  --branch main \
                  --testbed ubuntu-latest \
                  --threshold-measure latency \
                  --threshold-test t_test \
                  --threshold-max-sample-size 64 \
                  --threshold-upper-boundary 0.99 \
                  --thresholds-reset \
                  --error-on-alert \
                  --github-actions '${{ secrets.GITHUB_TOKEN }}' \
                  --file results.json \
                  "uv run pytest --benchmark-json results.json packages/python/benches/bench.py --benchmark-min-time 0.5"
