name: Run Benchmarks

on:
    pull_request:
        types: [opened, reopened, edited, synchronize]

jobs:
    benchmark_pr_branch:
        name: Benchmark pull request
        runs-on: self-hosted
        container:
            image: localhost:5000/qlit-bench-runner
        steps:
            - uses: actions/checkout@v6
            - uses: moonrepo/setup-rust@v1
              with:
                  cache-target: release
            - uses: astral-sh/setup-uv@v7
              with:
                  enable-cache: true
            - run: uv sync --locked
            - name: Run benchmarks
              run: uv run pytest --benchmark-json benchmark_results.json packages/python/benches/bench.py --benchmark-min-time 0.5
            - name: Upload benchmark results
              uses: actions/upload-artifact@v4
              with:
                  name: benchmark_results.json
                  path: ./benchmark_results.json
            - name: Upload pull request event
              uses: actions/upload-artifact@v4
              with:
                  name: event.json
                  path: ${{ github.event_path }}
