name: Benchmark Baseline

on:
    push:
        branches: main

jobs:
    benchmark_base_branch:
        name: Benchmark baseline
        permissions:
            checks: write
        runs-on: lille
        container:
            image: localhost:5000/qlit-bench-runner
        steps:
            - uses: actions/checkout@v6
            - uses: bencherdev/bencher@main
            - uses: moonrepo/setup-rust@v1
              with:
                  cache-target: release
            - name: Run benchmarks
              run: |
                  bencher run \
                  --project qlit-b20d40e-1lqksbyck7340 \
                  --branch main \
                  --start-point-reset \
                  --testbed lille \
                  "cargo bench"
